FROM quay.io/konflux-ci/buildah-task:latest@sha256:b2d6c32d1e05e91920cd4475b2761d58bb7ee11ad5dff3ecb59831c7572b4d0c

WORKDIR /scripts

COPY scripts/inject-icm.sh /scripts

LABEL \
  description="Inject an ICM (image content manifest) file with content sets for backwards compatibility." \
  io.k8s.description="Inject an ICM (image content manifest) file with content sets for backwards compatibility." \
  summary="Inject an ICM (image content manifest) file" \
  io.k8s.display-name="Inject an ICM (image content manifest) file" \
  name="Inject an ICM (image content manifest) file" \
  com.redhat.component="inject-icm"

ENTRYPOINT ["/scripts/inject-icm.sh"]

