apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/build-tasks-dockerfiles?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" && 
      (
      "source-container-build/***".pathChanged() ||
      ".tekton/source-container-build-push.yaml".pathChanged() ||
      ".tekton/build-pipeline.yaml".pathChanged()
      )
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: build-tasks-dockerfiles
    appstudio.openshift.io/component: source-container-build
    pipelines.appstudio.openshift.io/type: build
  name: source-container-build-on-push
  namespace: rhtap-build-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhtap-build-tenant/build-tasks-dockerfiles/source-container-build:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: source-container-build
  - name: build-source-image
    value: "true"
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
